name: CD

on:
  push:
    tags:
    - 'v*'

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
          pip install -r requirements/run.txt
          pip install -r requirements/test.txt
    - name: tag to version
      run: |
        echo "# Copyright (c) Semi-ATE" > starz/__init__.py
        echo "# Distributed under the terms of the MIT License" >> starz/__init__.py
        echo "__version__='${GITHUB_REF#refs/*/}'" >> starz/__init__.py
    - name: verify version
      run: cat starz/__init__.py
#    - name: Create package
#      run: python setup.py sdist
#    - name: Check package
#      run:  twine check dist/*
#    - name: Check manifest
#      run: check-manifest
#    - name: Upload to PyPI
#      env:
#        TWINE_USERNAME: __token__
#        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
#      run: python -m twine upload dist/*
