name: CI

on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Setup dependencies
        run: |
          pip install -r requirements/run.txt
          pip install -r requirements/test.txt
      - name: Show environment
        run: pip list
      - name: Run tests
        run: |
          echo tests disabled !!!!!
          pytest tests/ --cov=starz
      - name: Create package
        run: python setup.py sdist
      - name: Check package
        run: twine check dist/*
      - name: Check manifest (only on push to main)
        if: ${{ contains(github.ref, 'main') }}
        run: check-manifest

